// RequirementCard.tsx — displays a single ethical requirement

import {
    Card,
    CardContent,
    Box,
    Typography,
    Chip,
    IconButton,
    Tooltip,
    LinearProgress,
} from '@mui/material';
import {
    Edit as EditIcon,
    Delete as DeleteIcon,
    CheckCircle as AcceptIcon,
    Cancel as RejectIcon,
    AutoFixHigh as AutoIcon,
    Person as ManualIcon,
} from '@mui/icons-material';

// Principle colour map — high contrast
const PRINCIPLE_COLORS: Record<string, { light: string; dark: string; text: string; border: string }> = {
    fairness:       { light: '#e8f5e9', dark: '#1b5e20', text: '#1b5e20', border: '#2e7d32' },
    transparency:   { light: '#e1f5fe', dark: '#01579b', text: '#01579b', border: '#1565c0' },
    privacy:        { light: '#ffe0b2', dark: '#e65100', text: '#bf360c', border: '#ff6f00' },
    accountability: { light: '#f3e5f5', dark: '#4a148c', text: '#4a148c', border: '#6a1b9a' },
};

export interface Requirement {
    id?: string;
    name: string;
    principle: string;
    description?: string;
    specification?: Record<string, any>;
    status?: string;
    version?: number;
    elicited_automatically?: boolean;
    elicitation_reason?: string;
    confidence_score?: number;
    created_at?: string;
}

interface RequirementCardProps {
    requirement: Requirement;
    /** Show Accept / Reject buttons instead of Edit / Delete (for suggestions) */
    isSuggestion?: boolean;
    onAccept?: (req: Requirement) => void;
    onEdit?: (req: Requirement) => void;
    onReject?: (req: Requirement) => void;
    onDelete?: (req: Requirement) => void;
}

export default function RequirementCard({
    requirement,
    isSuggestion = false,
    onAccept,
    onEdit,
    onReject,
    onDelete,
}: RequirementCardProps) {
    const colors = PRINCIPLE_COLORS[requirement.principle] ?? {
        light: '#f5f5f5', dark: '#424242', text: '#212121', border: '#9e9e9e',
    };

    const rules: any[] = requirement.specification?.rules ?? [];

    return (
        <Card
            elevation={isSuggestion ? 3 : 1}
            sx={{
                borderLeft: isSuggestion ? undefined : `4px solid ${colors.border}`,
                bgcolor: isSuggestion ? colors.light : 'background.paper',
                transition: 'box-shadow 0.2s',
                '&:hover': { boxShadow: isSuggestion ? 6 : 3 },
            }}
        >
            <CardContent sx={{ p: 2.5, '&:last-child': { pb: 2.5 } }}>
                {/* Header row */}
                <Box sx={{ display: 'flex', alignItems: 'flex-start', gap: 1, mb: 1.5 }}>
                    <Box sx={{ flex: 1, minWidth: 0 }}>
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, flexWrap: 'wrap', mb: 0.5 }}>
                            <Typography variant="subtitle1" sx={{ fontWeight: 700, color: colors.text }}>
                                {requirement.name}
                            </Typography>
                            {requirement.elicited_automatically && (
                                <Tooltip title="Auto-generated by dataset analysis">
                                    <Chip
                                        icon={<AutoIcon sx={{ fontSize: '14px !important' }} />}
                                        label="Auto-generated"
                                        size="small"
                                        sx={{ 
                                            bgcolor: 'background.paper',
                                            color: colors.text, 
                                            border: `1.5px solid ${colors.border}`, 
                                            height: 20, 
                                            fontSize: '0.68rem',
                                            fontWeight: 600,
                                        }}
                                    />
                                </Tooltip>
                            )}
                            {!requirement.elicited_automatically && requirement.id && (
                                <Tooltip title="Manually created">
                                    <Chip
                                        icon={<ManualIcon sx={{ fontSize: '14px !important' }} />}
                                        label="Manual"
                                        size="small"
                                        variant="outlined"
                                        sx={{ height: 20, fontSize: '0.68rem' }}
                                    />
                                </Tooltip>
                            )}
                        </Box>

                        {/* Principle + Status chips */}
                        <Box sx={{ display: 'flex', gap: 0.75, flexWrap: 'wrap' }}>
                            <Chip
                                label={requirement.principle}
                                size="small"
                                sx={{ 
                                    bgcolor: isSuggestion ? colors.border : 'background.paper',
                                    color: isSuggestion ? '#fff' : colors.text, 
                                    border: `1.5px solid ${colors.border}`,
                                    fontWeight: 700, 
                                    textTransform: 'capitalize' 
                                }}
                            />
                            {requirement.status && (
                                <Chip
                                    label={requirement.status}
                                    size="small"
                                    color={
                                        requirement.status === 'active' ? 'success' :
                                        requirement.status === 'draft'  ? 'default' : 'warning'
                                    }
                                    variant="outlined"
                                />
                            )}
                            {requirement.version !== undefined && (
                                <Chip label={`v${requirement.version}`} size="small" variant="outlined" />
                            )}
                        </Box>
                    </Box>

                    {/* Action buttons */}
                    <Box sx={{ display: 'flex', gap: 0.5, flexShrink: 0 }}>
                        {isSuggestion && (
                            <>
                                <Tooltip title="Accept this requirement">
                                    <IconButton size="small" color="success" onClick={() => onAccept?.(requirement)}>
                                        <AcceptIcon fontSize="small" />
                                    </IconButton>
                                </Tooltip>
                                <Tooltip title="Reject / dismiss">
                                    <IconButton size="small" color="error" onClick={() => onReject?.(requirement)}>
                                        <RejectIcon fontSize="small" />
                                    </IconButton>
                                </Tooltip>
                            </>
                        )}
                        {!isSuggestion && (
                            <>
                                <Tooltip title="Edit">
                                    <IconButton size="small" onClick={() => onEdit?.(requirement)}>
                                        <EditIcon fontSize="small" />
                                    </IconButton>
                                </Tooltip>
                                <Tooltip title="Delete">
                                    <IconButton size="small" color="error" onClick={() => onDelete?.(requirement)}>
                                        <DeleteIcon fontSize="small" />
                                    </IconButton>
                                </Tooltip>
                            </>
                        )}
                    </Box>
                </Box>

                {/* Description */}
                {requirement.description && (
                    <Typography variant="body2" sx={{ mb: 1.5, lineHeight: 1.6, color: '#212121', fontWeight: 500 }}>
                        {requirement.description}
                    </Typography>
                )}

                {/* Elicitation reason */}
                {requirement.elicitation_reason && (
                    <Box sx={{ bgcolor: colors.light, borderLeft: `3px solid ${colors.border}`, borderRadius: 0.5, p: 1.2, mb: 1.5 }}>
                        <Typography variant="caption" sx={{ color: colors.text, fontStyle: 'italic', display: 'block' }}>
                            <strong style={{ color: colors.dark, fontWeight: 700 }}>Why generated:</strong> {requirement.elicitation_reason}
                        </Typography>
                    </Box>
                )}

                {/* Confidence score */}
                {requirement.confidence_score !== undefined && (
                    <Box sx={{ mb: 1.5 }}>
                        <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 0.5 }}>
                            <Typography variant="caption" sx={{ color: '#424242', fontWeight: 600 }}>Confidence</Typography>
                            <Typography variant="caption" sx={{ fontWeight: 700, color: colors.border }}>
                                {(requirement.confidence_score * 100).toFixed(0)}%
                            </Typography>
                        </Box>
                        <LinearProgress
                            variant="determinate"
                            value={requirement.confidence_score * 100}
                            sx={{
                                height: 8, borderRadius: 1,
                                bgcolor: 'rgba(0,0,0,0.06)',
                                '& .MuiLinearProgress-bar': { bgcolor: colors.border, borderRadius: 1 },
                            }}
                        />
                    </Box>
                )}

                {/* Threshold rules */}
                {rules.length > 0 && (
                    <Box>
                        <Typography variant="caption" sx={{ fontWeight: 700, color: colors.text, textTransform: 'uppercase', letterSpacing: 0.5 }}>
                            Thresholds
                        </Typography>
                        <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.75, mt: 0.75 }}>
                            {rules.map((rule, i) => (
                                <Chip
                                    key={i}
                                    label={`${rule.metric.replace(/_/g, ' ')} ${rule.operator} ${rule.value}`}
                                    size="small"
                                    sx={{ 
                                        bgcolor: isSuggestion ? colors.light : 'background.default',
                                        color: colors.text,
                                        border: `1px solid ${colors.border}`,
                                        fontSize: '0.7rem',
                                        fontWeight: 600,
                                    }}
                                />
                            ))}
                        </Box>
                    </Box>
                )}
            </CardContent>
        </Card>
    );
}
